// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNn-V05gzXRdprTwqInV8R9NXb5iBhTfI',
    appId: '1:28440167623:web:f48511d596e0f67d412ae2',
    messagingSenderId: '28440167623',
    projectId: 'taskachievers-1ebdf',
    authDomain: 'taskachievers-1ebdf.firebaseapp.com',
    storageBucket: 'taskachievers-1ebdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUAqB6F1pVesQNDDxW03bmIQSw19PEZ0E',
    appId: '1:28440167623:android:94b845e6b00000f0412ae2',
    messagingSenderId: '28440167623',
    projectId: 'taskachievers-1ebdf',
    storageBucket: 'taskachievers-1ebdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuqin7tIAAZgLCnurTzVrRKfKJweoOdv8',
    appId: '1:28440167623:ios:31b98d0b68e9f160412ae2',
    messagingSenderId: '28440167623',
    projectId: 'taskachievers-1ebdf',
    storageBucket: 'taskachievers-1ebdf.appspot.com',
    iosClientId: '28440167623-nnl3g317grv91lr14o09g6tjpenfe5f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.achieversApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuqin7tIAAZgLCnurTzVrRKfKJweoOdv8',
    appId: '1:28440167623:ios:31b98d0b68e9f160412ae2',
    messagingSenderId: '28440167623',
    projectId: 'taskachievers-1ebdf',
    storageBucket: 'taskachievers-1ebdf.appspot.com',
    iosClientId: '28440167623-nnl3g317grv91lr14o09g6tjpenfe5f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.achieversApp',
  );
}
